# Generated by Django 4.2.10 on 2024-03-19 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_composition_collaborative_artist_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Артист', 'verbose_name_plural': 'Артисты'},
        ),
        migrations.AlterModelOptions(
            name='composition',
            options={'verbose_name': 'Композиция', 'verbose_name_plural': 'Композиции'},
        ),
        migrations.AddField(
            model_name='composition',
            name='artists_slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='composition',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compositions', to='main.artist'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='collaborative_artist',
            field=models.ManyToManyField(blank=True, related_name='collaborative_compositions', to='main.artist'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='featured_artist',
            field=models.ManyToManyField(blank=True, related_name='featured_compositions', to='main.artist'),
        ),
    ]
