# Generated by Django 4.2.10 on 2024-03-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_composition_artists_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='collaborative_artist',
        ),
        migrations.RemoveField(
            model_name='composition',
            name='artist',
        ),
        migrations.AddField(
            model_name='composition',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='collaborative_compositions', to='main.artist'),
        ),
    ]
