# Generated by Django 4.2 on 2024-04-29 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_composition_collaborative_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='artist',
            field=models.ManyToManyField(related_name='compositions', to='main.artist', verbose_name='Артист (Зажать CTRL чтобы выбрать несколько)'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='composition_type',
            field=models.CharField(choices=[('SOLO', 'Solo'), ('FEAT', 'Feature'), ('COLLAB', 'Collaborative'), ('COLLAB_FEAT', 'Collaborative Feature')], default='SOLO', max_length=11, verbose_name='Тип композиции'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='featured_artist',
            field=models.ManyToManyField(blank=True, related_name='featured_compositions', to='main.artist', verbose_name='Артист на фите (Зажать CTRL чтобы выбрать несколько)'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='release_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата релиза'),
        ),
        migrations.AlterField(
            model_name='composition',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
