# Generated by Django 4.2 on 2024-04-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_artist_photo_alter_artist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
    ]
