# Generated by Django 4.2 on 2024-05-14 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_composition_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='composition',
            options={'ordering': ['-release_date'], 'verbose_name': 'Композиция', 'verbose_name_plural': 'Композиции'},
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(choices=[(0, 'Appalling'), (1, 'Horrible'), (2, 'Very Bad'), (4, 'Bad'), (5, 'Average'), (6, 'Fine'), (7, 'Good'), (8, 'Very Good'), (9, 'Great'), (10, 'Masterpiece')])),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_composition', to='main.composition', verbose_name='Композиция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_user', to=settings.AUTH_USER_MODEL, verbose_name='Юзер')),
            ],
        ),
    ]
